cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules

stages:
  - build
  - package
  - deploy

build:
  image: mongo
  stage: build
  script:
    - apt update
    - apt install -y nodejs npm
    - npm install -g --save-dev nodemon
    - npm install -g express --save
    - npm install -g mongoose --save
    - mongod &
    - npm install
    - npm start &
  artifacts:
    paths:
      - ./api

package:
  stage: package
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login "${REGISTRY_URL}" -u "${GITLAB_USER}" -p "${GITLAB_TOKEN}"
    - docker build -t "$REGISTRY_URL"/rherrera1/test23ppl .
    - docker push "$REGISTRY_URL"/rherrera1/test23ppl


deploy:
  stage: deploy
  image: google/cloud-sdk:latest
  script:
    - echo "$SERVICE_ACCOUNT_KEY" | base64 -d > gke-token.json
    - gcloud auth activate-service-account --key-file=gke-token.json
    - gcloud config set project prueba-nisum
    - gcloud config set container/cluster my-cluster
    - gcloud config set compute/zone us-central1-a
    - gcloud container clusters get-credentials nodejsapp-cluster --zone us-central1-a
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - ./kubectl create secret generic registry.gitlab.com --from-literal=Gitlab_User=$"GITLAB_USER" --from-literal=Gitlab_Password=$"GITLAB_TOKEN" --dry-run -o yaml | kubectl apply -f -
    - ./kubectl apply -f deploy.yml
    - ./kubectl apply -f service.yaml
