apiVersion: apps/v1
kind: Deployment
metadata:
  name: v23ppl
spec:
  selector:
    matchLabels:
      app: v23ppl
  template:
    metadata:
      labels:
        app: v23ppl
    spec:
      containers:
        - name: v23ppl
          image: registry.gitlab.com/rherrera1/test23ppl
          ports:
          - containerPort: 1337
      imagePullSecrets:
        - name: registry.gitlab.com
